
# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  sonarcloud:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
    with:
      # Disabling shallow clone is recommended for improving relevancy of reporting
      fetch-depth: 0
  - name: SonarCloud Scan
    uses: sonarsource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.8
      uses: actions/setup-node@v1
      with:
        node-version: 12.8
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build Library
      run: npm run build selection-list --prod
    - name: Build
      run: npm run build -- --prod
    - name: Test
      run: npm run test-ci
    #- name: E2E
    #  run: npm run e2e-ci
